[build]
  command = "bun run build"  # or whatever your build command is
  publish = "dist"           # or whatever your publish directory is

[context.main]
  command = "bun run build"
  publish = "dist"

[context.stage]
  command = "bun run build"
  publish = "dist"
  environment = { NODE_ENV = "staging" }

[context.deploy-preview]
  command = "bun run build"
  publish = "dist"